import dynamic from "next/dynamic";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
const Header = dynamic(() => import("../Components/Header"));
const Footer = dynamic(() => import("../Components/Footer"));
const ScrollToTop = dynamic(() => import("../Components/Content/ScrollToTop"));
import NextTopLoader from "nextjs-toploader";
import Script from "next/script";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body
        className={`${poppins.variable} font-poppins flex flex-col antialiased`}
      >
        <Header />
        <main className="flex h-full w-full flex-auto flex-col">
          {children}
          <ScrollToTop />
        </main>
        <Footer />

        <NextTopLoader
          color="#cc0000"
          height={4}
          showSpinner={true}
          zIndex={1600}
        />
        {process.env.NODE_ENV === "production" && (
          <>
            <Script
              src={`https://www.googletagmanager.com/gtag/js?id=G-YK7RLEENZD`}
              strategy="afterInteractive"
            />
            <Script id="google-analytics" strategy="afterInteractive">
              {`
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());

              gtag('config', 'G-YK7RLEENZD');
            `}
            </Script>
          </>
        )}
      </body>
    </html>
  );
}
